CREATE TABLE IF NOT EXISTS hits(
    id bigint generated by default as identity primary key,
    app varchar(256),
    uri varchar(2048),
    ip varchar(16),
    timestamp timestamp without time zone
);