CREATE TABLE IF NOT EXISTS hits(
    id bigint generated by default as identity primary key,
    app varchar(256) not null,
    uri varchar(2048) not null,
    ip varchar(16) not null,
    timestamp timestamp without time zone
);