DROP TABLE IF EXISTS compilations cascade;
DROP TABLE IF EXISTS requests cascade;
DROP TABLE IF EXISTS events cascade;
DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS categories cascade;
DROP TABLE IF EXISTS locations cascade;
DROP TABLE IF EXISTS event_compilation cascade;
DROP TABLE IF EXISTS comments cascade;

CREATE TABLE IF NOT EXISTS users
(
    user_id bigint generated by default as identity primary key,
    name    varchar(128) not null,
    email   varchar(128) not null unique,
    banCommentsPeriod timestamp without time zone,
    CONSTRAINT UQ_USER_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id bigint generated by default as identity primary key,
    name        varchar(64) NOT NULL,
    CONSTRAINT UC_CATEGORIES_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    event_id           bigint generated by default as identity primary key,
    created_on         timestamp without time zone,
    category_id        bigint references categories (category_id) NOT NULL,
    annotation         varchar(1024),
    description        varchar(4096),
    confirmed_requests bigint,
    event_date         timestamp without time zone,
    initiator_id       bigint REFERENCES users (user_id)          NOT NULL,
    lat                numeric                                    NOT NULL,
    lon                numeric                                    NOT NULL,
    paid               boolean,
    participant_limit  int,
    published_on       timestamp without time zone,
    request_moderation boolean,
    state              varchar(64),
    title              varchar(256)                               NOT NULL,
    views              bigint
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id   bigint generated by default as identity primary key,
    created      timestamp without time zone,
    event_id     bigint references events (event_id),
    requester_id bigint references users (user_id),
    status       varchar(64),
    UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id bigint generated by default as identity primary key,
    pinned         boolean,
    title          varchar(64) not null
);

CREATE TABLE IF NOT EXISTS event_compilation
(
    event_id       bigint references events (event_id),
    compilation_id bigint references compilations (compilation_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id     bigint generated by default as identity primary key,
    text           varchar(4096)                     not null,
    created_on     timestamp without time zone       not null,
    commentator_id bigint references users (user_id) not null,
    status         varchar(64),
    update_on      timestamp without time zone       not null,
    event_id       bigint references events (event_id)
);



